[package]
# Package names are always "SCOPE/NAME"
# They can inclde lowercase letters, numbers, and dashes.
name = "sunyesta/art-room"

# Descriptions are free-form. These will be used as part of package listings
# and search results.
description = "Art rooms are cool!"

# Versions follow Semantic Versioning.
# https://semver.org/
version = "0.0.1"

# Contains an SPDX License Expression.
# Licenses are required for publishing code to public registries.
# license = "MIT OR Apache-2.0"

# The author list is a free-form list, but conventionally contains names and
# email addresses.
authors = ["sunyesta"]

# Packages belong to a "realm", which helps prevent using code in the wrong
# context. For now, we have "server" and "shared" realms.
# The server realm should only be used for packages which shouldn't be replicated.
realm = "shared"

# Wally supports multiple registries.
# This feature can be used to have split public/private registries to
# keep internal code private and isolated.
registry = "https://github.com/upliftgames/wally-index"

# You can also specify files to include or exclude from the package
# By default gitignore files are respected and Wally won't include hidden
# files/directories or packages downloaded by Wally.
# include = []
# exclude = ["node_modules"]

[dependencies]
# Most dependencies will look like this.
#
# The name on the left is an alias. It defines what name we would like to
# use to refer to this package.
#
# The value on the right will usually be a string of the form
#   "SCOPE/NAME@VERSION_REQ"
# Versions are SemVer version requirements. The default behavior matches
# Cargo, or npm with the `^` version specifier.


Loader = "sleitnick/loader@2.0.0"
Component = "sleitnick/component@2.4.8"
Promise = "evaera/promise@4.0.0"
Trove = "sleitnick/trove@0.5.0"
Signal = "sleitnick/signal@1.5.0"
TableUtil = "sleitnick/table-util@1.2.0"
Shake = "sleitnick/shake@0.1.7"
Streamable = "sleitnick/streamable@1.2.4"
smartbone2 = "jakeywastaken/smartbone-2@0.4.2"
WindShake = "boatbomber/windshake@2.0.3"
Input = "sleitnick/input@2.3.0"
Comm = "sleitnick/comm@1.0.1"
